backend:
  name: git-gateway
  branch: main

media_folder: imagens
public_folder: imagens

collections:
  - name: produtos
    label: Produtos Lacrados
    files:
      - label: Lista de Produtos
        name: produtos
        file: produtos.json
        fields:
          - label: Produtos
            name: items
            widget: list
            fields:
              - { label: Nome, name: nome, widget: string }
              - label: Idioma
                name: lingua
                widget: select
                options:
                  - { label: "🇧🇷 Português (PT-BR)", value: "🇧🇷" }
                  - { label: "🇺🇸 Inglês (EN)", value: "🇺🇸" }
                  - { label: "🇯🇵 Japonês (JP)", value: "🇯🇵" }
              - { label: Edição, name: edicao, widget: string, hint: "Ex: Rivais Predestinados, 151, Obsidiana Em Chamas..." }
              - { label: Tipo, name: tipo, widget: string, hint: "Ex: Caixa de Booster, Blister, Kit..." }
              - { label: "Preço (R$)", name: preco, widget: number, value_type: float }
              - { label: Foto do produto, name: imagem, widget: image, required: false, default: "" }

  - name: cartas
    label: Cartas em Destaque
    files:
      - label: Lista de Cartas
        name: cartas
        file: cartas.json
        fields:
          - label: Cartas
            name: items
            widget: list
            fields:
              - { label: Nome da Carta, name: nome, widget: string }
              - { label: Edição, name: edicao, widget: string }
              - { label: "Número (ex. 006/165)", name: numero, widget: string }
              - { label: "Preço (R$)", name: preco, widget: number, value_type: float }
              - { label: Foto da Carta, name: imagem, widget: image, required: false, default: "" }
              - { label: Descrição, name: descricao, widget: string }
